# Generated by Django 5.0.7 on 2024-10-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotrudnic',
            name='img',
            field=models.ImageField(upload_to='Woor', verbose_name='Изображения сотрудника'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(verbose_name='Срок до'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(upload_to='Woork', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Названия задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='who_develops',
            field=models.ManyToManyField(related_name='devs', to='main.sotrudnic'),
        ),
    ]
